version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ReviewDb=mongodb://mongodb:27017
      - ConnectionStrings__Redis=redis:6379
      - CLOUD_FLARE_ACCOUNT_ID=996e61a9da1f0f49e4ad5770932100d2
      - CLOUD_FLARE_API_TOKEN=cYgcxEz_yWt07vFaKv2qJ7Wr0g6IJF-vzDtWlH7c
      - X-Api-Key=3R2YJKjzQeRG9+Bx5P8M3nB+d8v6TgRWk3yzFjZa+Eo=
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
